---
app_name: 'cloudport'
app_repo: 'https://github.com/ivanilves/CloudPort.git'
app_author: 'Ivan Ilves <ivan.ilves@gmail.com>'
app_version: 'develop'
app_env: 'production'
app_user_home: '/deploy'
app_path: "{{ app_user_home }}/{{ app_name }}"
app_user_name: "{{ app_name }}"
app_group_name: "{{ app_name }}"
app_conf_file: "/etc/default/{{ app_name }}"

app_reload_script: "{{ app_path }}/script/tools/reload-service"
app_pid_dir_script: "{{ app_path }}/script/tools/ensure-pid-dir"

ruby_version: '2.2.6'
ruby_base_version: '2.2.0'
bundler_version: '1.13.6'
bundle_without: 'development test'
bundle_gem_path: "{{ app_path }}/vendor/bundle/ruby/{{ ruby_base_version }}"

mysql_app_username: "{{ app_name }}"

ptu_repo: 'https://github.com/ivanilves/ptu.git'
ptu_version: 'master'
ptu_path: "{{ app_user_home }}/ptu"
