---
- hosts: cloudport
  become: yes
  tasks:
    - name: Update operating system
      apt: upgrade=dist update_cache=yes
           dpkg_options='force-confold,force-confdef'
      notify:
        - Remove unneeded packages
        - Clean package cache
    - name: Install unzip
      apt: pkg=unzip state=latest
    - name: Install development essentials
      apt: pkg={{ item }} state=latest
      with_items:
        - git
        - nodejs
        - build-essential
        - libssl-dev
        - libreadline-dev
        - libgmp-dev
    - name: Install Nginx HTTP server/reverse proxy
      apt: pkg=nginx state=latest
    - name: Ensure Nginx service enabled and started
      service: name=nginx enabled=yes state=started
    - name: Install Redis in-memory data structure store
      apt: pkg=redis-server state=latest
    - name: Ensure Redis service enabled and started
      service: name=redis-server enabled=yes state=started
  handlers:
    - name: Remove unneeded packages
      shell: apt-get -y autoremove
      args:
        warn: no
    - name: Clean package cache
      shell: apt-get clean
      args:
        warn: no
